export const ZONES = ["Centro", "Norte", "Sul", "Leste", "Oeste"] as const;
export const USE_TYPES = [
  "passeio",
  "brincadeira",
  "treino",
  "socializacao",
  "creche",
  "pernoite",
  "hospedagem",
  "evento",
] as const;
export const DOG_SIZES = ["pequeno", "medio", "grande"] as const;
export const AMENITIES = ["cercado", "gramado", "agua", "sombra", "agility"] as const;
export const TIME_SLOTS = ["manha", "tarde", "noite"] as const;
export const SPACE_TYPES = ["quintal", "campo", "salao", "agility", "piscina", "terraco"] as const;

export type Zone = (typeof ZONES)[number];
export type UseType = (typeof USE_TYPES)[number];
export type DogSize = (typeof DOG_SIZES)[number];
export type Amenity = (typeof AMENITIES)[number];
export type TimeSlot = (typeof TIME_SLOTS)[number];
export type SpaceType = (typeof SPACE_TYPES)[number];

export type Space = {
  slug: string;
  name: string;
  zone: Zone;
  neighborhoodLabel: string;
  /** Nome do bairro sem o prefixo, para busca e autocomplete. */
  neighborhood: string;
  approximateMapArea: string;
  spaceType: SpaceType;
  allowedUses: UseType[];
  dogSizes: DogSize[];
  maxDogs: number;
  availableSlots: TimeSlot[];
  amenities: Amenity[];
  imageUrl: string;
  imageAlt: string;
  description: string;
};

export const AMENITY_LABELS: Record<Amenity, string> = {
  cercado: "Área cercada",
  gramado: "Gramado",
  agua: "Água disponível",
  sombra: "Sombra",
  agility: "Itens de treino",
};

export const USE_TYPE_LABELS: Record<UseType, string> = {
  passeio: "Passeio tranquilo",
  brincadeira: "Brincadeira livre",
  treino: "Treino e adestramento",
  socializacao: "Socialização",
  creche: "Creche por um dia",
  pernoite: "Pernoite",
  hospedagem: "Hospedagem por vários dias",
  evento: "Festa ou evento",
};

/** Ocasiões em que o cão dorme fora: exigem espaço abrigado. */
export const OVERNIGHT_USES: UseType[] = ["pernoite", "hospedagem"];

export const DOG_SIZE_LABELS: Record<DogSize, string> = {
  pequeno: "Pequeno porte",
  medio: "Médio porte",
  grande: "Grande porte",
};

export const TIME_SLOT_LABELS: Record<TimeSlot, string> = {
  manha: "Manhã",
  tarde: "Tarde",
  noite: "Noite",
};

export const SPACE_TYPE_LABELS: Record<SpaceType, string> = {
  quintal: "Quintal",
  campo: "Campo aberto",
  salao: "Salão coberto",
  agility: "Circuito de treino",
  piscina: "Piscina para cães",
  terraco: "Terraço",
};

const photo = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=85`;

export const SPACES: Space[] = [
  // Centro
  {
    slug: "patio-santa-cecilia",
    name: "Pátio Santa Cecília",
    zone: "Centro",
    neighborhoodLabel: "Região de Santa Cecília",
    neighborhood: "Santa Cecília",
    approximateMapArea: "Centro, em um trecho residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "treino", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "sombra", "agility"],
    imageUrl: photo("1594498653385-d5172c532c00"),
    imageAlt: "Quintal gramado cercado por vegetação",
    description: "Quintal compacto para rotinas de treino e passeio no meio da cidade.",
  },
  {
    slug: "terraco-bela-vista",
    name: "Terraço Bela Vista",
    zone: "Centro",
    neighborhoodLabel: "Região da Bela Vista",
    neighborhood: "Bela Vista",
    approximateMapArea: "Centro, em uma área de acesso fácil",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1624018171446-c4f0b942cf87"),
    imageAlt: "Terraço com jardim e canteiros floridos",
    description: "Terraço abrigado para encontros calmos com cães pequenos.",
  },
  {
    slug: "jardim-da-consolacao",
    name: "Jardim da Consolação",
    zone: "Centro",
    neighborhoodLabel: "Região da Consolação",
    neighborhood: "Consolação",
    approximateMapArea: "Centro, próximo a um corredor arborizado",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino", "creche", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua"],
    imageUrl: photo("1778683326192-898fc982e6a6"),
    imageAlt: "Jardim cercado por muro de madeira",
    description: "Jardim reservado, bom para os primeiros encontros entre cães.",
  },
  {
    slug: "salao-da-liberdade",
    name: "Salão da Liberdade",
    zone: "Centro",
    neighborhoodLabel: "Região da Liberdade",
    neighborhood: "Liberdade",
    approximateMapArea: "Centro, em uma quadra comercial",
    spaceType: "salao",
    allowedUses: ["treino", "socializacao", "brincadeira", "creche", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "agility"],
    imageUrl: photo("1538307602205-80b5c2ff26ec"),
    imageAlt: "Área externa com mesas e piso coberto",
    description: "Salão coberto que resolve o dia de chuva sem cancelar o treino.",
  },
  {
    slug: "quintal-higienopolis",
    name: "Quintal Higienópolis",
    zone: "Centro",
    neighborhoodLabel: "Região de Higienópolis",
    neighborhood: "Higienópolis",
    approximateMapArea: "Centro, em uma rua arborizada",
    spaceType: "quintal",
    allowedUses: ["passeio", "socializacao", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 1,
    availableSlots: ["manha"],
    amenities: ["gramado", "sombra"],
    imageUrl: photo("1596481768453-8befafc2d7ae"),
    imageAlt: "Jardim denso com caminho de pedras",
    description: "Espaço tranquilo para um cão de cada vez, sem outros por perto.",
  },
  {
    slug: "deck-da-republica",
    name: "Deck da República",
    zone: "Centro",
    neighborhoodLabel: "Região da República",
    neighborhood: "República",
    approximateMapArea: "Centro, perto de uma praça",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1719324924230-63781a3f18b9"),
    imageAlt: "Quintal com gramado e casa ao fundo",
    description: "Deck cercado para fim de tarde com outros tutores.",
  },

  // Norte
  {
    slug: "campo-do-sol",
    name: "Campo do Sol",
    zone: "Norte",
    neighborhoodLabel: "Região de Santana",
    neighborhood: "Santana",
    approximateMapArea: "Norte, próximo a uma faixa de parques",
    spaceType: "campo",
    allowedUses: ["brincadeira", "passeio", "socializacao", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde"],
    amenities: ["gramado", "agua", "sombra"],
    imageUrl: photo("1585107328143-be98f5f6119b"),
    imageAlt: "Campo aberto com grama alta e árvores",
    description: "Campo aberto para gastar energia com espaço de sobra.",
  },
  {
    slug: "patio-das-oliveiras",
    name: "Pátio das Oliveiras",
    zone: "Norte",
    neighborhoodLabel: "Região de Tucuruvi",
    neighborhood: "Tucuruvi",
    approximateMapArea: "Norte, próximo a áreas arborizadas",
    spaceType: "quintal",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1715934514075-06f0dbda1c09"),
    imageAlt: "Quintal cercado com grama e muro claro",
    description: "Pátio tranquilo para encontros e passeios sem pressa.",
  },
  {
    slug: "gramado-casa-verde",
    name: "Gramado Casa Verde",
    zone: "Norte",
    neighborhoodLabel: "Região da Casa Verde",
    neighborhood: "Casa Verde",
    approximateMapArea: "Norte, em uma área de casas",
    spaceType: "campo",
    allowedUses: ["brincadeira", "treino", "passeio"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde"],
    amenities: ["gramado", "agua", "agility"],
    imageUrl: photo("1719324923613-ff0884b031ed"),
    imageAlt: "Gramado amplo ao lado de uma construção",
    description: "Gramado largo, pensado para cães que correm de verdade.",
  },
  {
    slug: "arena-vila-guilherme",
    name: "Arena Vila Guilherme",
    zone: "Norte",
    neighborhoodLabel: "Região de Vila Guilherme",
    neighborhood: "Vila Guilherme",
    approximateMapArea: "Norte, em uma zona mista",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "gramado", "agility", "agua"],
    imageUrl: photo("1705980505348-222bc8724138"),
    imageAlt: "Área externa com piso e mobiliário de jardim",
    description: "Circuito montado para treino de obstáculos, com foco em uma dupla por vez.",
  },
  {
    slug: "bosque-do-mandaqui",
    name: "Bosque do Mandaqui",
    zone: "Norte",
    neighborhoodLabel: "Região do Mandaqui",
    neighborhood: "Mandaqui",
    approximateMapArea: "Norte, em uma encosta arborizada",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde"],
    amenities: ["gramado", "sombra", "agua"],
    imageUrl: photo("1695550056778-de79c8cd909e"),
    imageAlt: "Área de convívio ao ar livre com guarda-sol",
    description: "Bosque sombreado que aguenta grupos maiores sem ficar apertado.",
  },
  {
    slug: "quintal-do-jacana",
    name: "Quintal do Jaçanã",
    zone: "Norte",
    neighborhoodLabel: "Região do Jaçanã",
    neighborhood: "Jaçanã",
    approximateMapArea: "Norte, em um bairro residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["manha", "noite"],
    amenities: ["cercado", "gramado", "sombra"],
    imageUrl: photo("1561283890-5d858c23b2ea"),
    imageAlt: "Campo gramado aberto sob céu limpo",
    description: "Quintal cercado e reservado para cães pequenos.",
  },

  // Sul
  {
    slug: "jardim-da-colina",
    name: "Jardim da Colina",
    zone: "Sul",
    neighborhoodLabel: "Região de Vila Mariana",
    neighborhood: "Vila Mariana",
    approximateMapArea: "Sul, em uma área residencial arborizada",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1602684379319-1de467ca74e5"),
    imageAlt: "Gramado cercado com árvores ao redor",
    description: "Jardim tranquilo para encontros em ritmo leve.",
  },
  {
    slug: "gramado-do-vale",
    name: "Gramado do Vale",
    zone: "Sul",
    neighborhoodLabel: "Região de Santo Amaro",
    neighborhood: "Santo Amaro",
    approximateMapArea: "Sul, em uma área de quintais amplos",
    spaceType: "campo",
    allowedUses: ["brincadeira", "treino", "socializacao", "passeio", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "agility"],
    imageUrl: photo("1612353413650-314b2f5146ed"),
    imageAlt: "Cães correndo em um campo gramado",
    description: "Gramado versátil, o mais flexível do catálogo para grupos.",
  },
  {
    slug: "recanto-do-ceu",
    name: "Recanto do Céu",
    zone: "Sul",
    neighborhoodLabel: "Região da Saúde",
    neighborhood: "Saúde",
    approximateMapArea: "Sul, perto de praças locais",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["tarde"],
    amenities: ["cercado", "gramado", "sombra"],
    imageUrl: photo("1608200765700-ba7ff78b6dd0"),
    imageAlt: "Caminho de parque com cães ao fundo",
    description: "Recanto arejado para a rotina de fim de tarde.",
  },
  {
    slug: "piscina-de-moema",
    name: "Piscina de Moema",
    zone: "Sul",
    neighborhoodLabel: "Região de Moema",
    neighborhood: "Moema",
    approximateMapArea: "Sul, em uma quadra residencial",
    spaceType: "piscina",
    allowedUses: ["brincadeira", "socializacao", "passeio", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1619333774340-3a878585c2e4"),
    imageAlt: "Área verde arborizada com sombra",
    description: "Piscina rasa para cães, com área de descanso na sombra.",
  },
  {
    slug: "campo-belo-aberto",
    name: "Campo Belo Aberto",
    zone: "Sul",
    neighborhoodLabel: "Região do Campo Belo",
    neighborhood: "Campo Belo",
    approximateMapArea: "Sul, em uma área plana",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "treino", "socializacao", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 8,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "sombra", "agility"],
    imageUrl: photo("1703733569670-f36996a8ca1d"),
    imageAlt: "Cães correndo juntos em gramado amplo",
    description: "O maior do catálogo: cabe grupo grande e aceita qualquer uso.",
  },
  {
    slug: "patio-do-ipiranga",
    name: "Pátio do Ipiranga",
    zone: "Sul",
    neighborhoodLabel: "Região do Ipiranga",
    neighborhood: "Ipiranga",
    approximateMapArea: "Sul, próximo a um parque histórico",
    spaceType: "quintal",
    allowedUses: ["passeio", "treino", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["manha", "noite"],
    amenities: ["cercado", "gramado", "agility"],
    imageUrl: photo("1667230228326-c881966e2a29"),
    imageAlt: "Cães brincando em área cercada",
    description: "Pátio cercado para treino de cães maiores, sem plateia.",
  },

  // Leste
  {
    slug: "quintal-do-lago",
    name: "Quintal do Lago",
    zone: "Leste",
    neighborhoodLabel: "Região do Tatuapé",
    neighborhood: "Tatuapé",
    approximateMapArea: "Leste, em uma área de casas e praças",
    spaceType: "quintal",
    allowedUses: ["brincadeira", "socializacao", "passeio", "creche", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "gramado", "agua"],
    imageUrl: photo("1558385952-504347abdceb"),
    imageAlt: "Pessoas e cães em gramado de parque",
    description: "Espaço aberto para cães que gostam de companhia.",
  },
  {
    slug: "jardim-do-arco",
    name: "Jardim do Arco",
    zone: "Leste",
    neighborhoodLabel: "Região de Anália Franco",
    neighborhood: "Anália Franco",
    approximateMapArea: "Leste, em uma área residencial",
    spaceType: "quintal",
    allowedUses: ["brincadeira", "treino", "passeio", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["tarde", "noite"],
    amenities: ["gramado", "agility", "agua"],
    imageUrl: photo("1621851327323-bc467dd48d86"),
    imageAlt: "Cão correndo em gramado cercado",
    description: "Área aberta pensada para gastar energia com foco.",
  },
  {
    slug: "galpao-da-mooca",
    name: "Galpão da Mooca",
    zone: "Leste",
    neighborhoodLabel: "Região da Mooca",
    neighborhood: "Mooca",
    approximateMapArea: "Leste, em um trecho industrial revitalizado",
    spaceType: "salao",
    allowedUses: ["treino", "brincadeira", "socializacao", "creche", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "agility"],
    imageUrl: photo("1514373941175-0a141072bbc8"),
    imageAlt: "Campo gramado com banco e árvores",
    description: "Galpão coberto e cercado, útil quando o tempo fecha.",
  },
  {
    slug: "campo-da-penha",
    name: "Campo da Penha",
    zone: "Leste",
    neighborhoodLabel: "Região da Penha",
    neighborhood: "Penha",
    approximateMapArea: "Leste, perto de uma área verde",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha"],
    amenities: ["gramado", "sombra", "agua"],
    imageUrl: photo("1619316741699-b96740c17b63"),
    imageAlt: "Gramado extenso com árvores ao fundo",
    description: "Campo de manhã cedo, quando o movimento ainda é baixo.",
  },
  {
    slug: "circuito-vila-formosa",
    name: "Circuito Vila Formosa",
    zone: "Leste",
    neighborhoodLabel: "Região de Vila Formosa",
    neighborhood: "Vila Formosa",
    approximateMapArea: "Leste, em uma rua residencial",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira", "passeio"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "gramado", "agility"],
    imageUrl: photo("1703733574403-e2e42e3c5bda"),
    imageAlt: "Cães correndo em parque cercado",
    description: "Circuito de obstáculos dimensionado para cães menores.",
  },
  {
    slug: "terraco-do-belem",
    name: "Terraço do Belém",
    zone: "Leste",
    neighborhoodLabel: "Região do Belém",
    neighborhood: "Belém",
    approximateMapArea: "Leste, em uma quadra tranquila",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1512134687100-628ef82e6626"),
    imageAlt: "Gramado verde com árvores ao redor",
    description: "Terraço cercado, bom para cães pequenos e tímidos.",
  },

  // Oeste
  {
    slug: "quintal-da-praca",
    name: "Quintal da Praça",
    zone: "Oeste",
    neighborhoodLabel: "Região de Pinheiros",
    neighborhood: "Pinheiros",
    approximateMapArea: "Oeste, perto da área verde urbana",
    spaceType: "quintal",
    allowedUses: ["treino", "brincadeira", "passeio", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "sombra", "agility"],
    imageUrl: photo("1569203685368-118435c389dd"),
    imageAlt: "Cães correndo em gramado cercado",
    description: "Área ampla e cercada para treinar com espaço e foco.",
  },
  {
    slug: "bosque-claro",
    name: "Bosque Claro",
    zone: "Oeste",
    neighborhoodLabel: "Região do Butantã",
    neighborhood: "Butantã",
    approximateMapArea: "Oeste, em uma zona mais arborizada",
    spaceType: "campo",
    allowedUses: ["passeio", "treino", "brincadeira", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde"],
    amenities: ["gramado", "sombra", "agility"],
    imageUrl: photo("1784593149239-7c0073ea5951"),
    imageAlt: "Quintal cercado por cerca de madeira",
    description: "Refúgio verde para uma rotina mais ativa.",
  },
  {
    slug: "casa-da-serra",
    name: "Casa da Serra",
    zone: "Oeste",
    neighborhoodLabel: "Região de Alto de Pinheiros",
    neighborhood: "Alto de Pinheiros",
    approximateMapArea: "Oeste, em área de casas",
    spaceType: "quintal",
    allowedUses: ["treino", "socializacao", "brincadeira", "passeio", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "gramado", "agua", "agility"],
    imageUrl: photo("1758208137355-223fa672cbe2"),
    imageAlt: "Quintal com gramado e cerca alta",
    description: "Quintal amplo para encontros com mais energia.",
  },
  {
    slug: "piscina-das-perdizes",
    name: "Piscina das Perdizes",
    zone: "Oeste",
    neighborhoodLabel: "Região de Perdizes",
    neighborhood: "Perdizes",
    approximateMapArea: "Oeste, em uma rua residencial",
    spaceType: "piscina",
    allowedUses: ["brincadeira", "socializacao", "passeio", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1734079692147-c6fc9438a2d0"),
    imageAlt: "Jardim com deck de madeira e vegetação",
    description: "Piscina para cães com área seca ao lado para descanso.",
  },
  {
    slug: "patio-vila-madalena",
    name: "Pátio Vila Madalena",
    zone: "Oeste",
    neighborhoodLabel: "Região de Vila Madalena",
    neighborhood: "Vila Madalena",
    approximateMapArea: "Oeste, em uma ladeira tranquila",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 2,
    availableSlots: ["tarde", "noite"],
    amenities: ["cercado", "sombra"],
    imageUrl: photo("1786654026603-54c654c05c18"),
    imageAlt: "Terraço com gramado e guarda-sol",
    description: "Pátio pequeno e reservado, no ritmo de quem quer sossego.",
  },
  {
    slug: "arena-da-lapa",
    name: "Arena da Lapa",
    zone: "Oeste",
    neighborhoodLabel: "Região da Lapa",
    neighborhood: "Lapa",
    approximateMapArea: "Oeste, próximo a uma via movimentada",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira", "passeio", "evento"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agility", "agua"],
    imageUrl: photo("1684867430916-ede9dc95eca5"),
    imageAlt: "Terreno gramado delimitado por muro",
    description: "Arena de treino com espaço para turma inteira de adestramento.",
  },
];

/** Bairros que hoje têm espaço no catálogo, para filtrar a busca. */
export const CATALOG_NEIGHBORHOODS: string[] = [...new Set(SPACES.map((space) => space.neighborhood))].sort((a, b) =>
  a.localeCompare(b, "pt-BR"),
);

/**
 * Bairros de São Paulo oferecidos no formulário de solicitação. Inclui os do
 * catálogo e outros bairros onde ainda não temos espaço, para que o tutor
 * consiga dizer onde precisa mesmo que a região ainda não esteja atendida.
 */
export const SP_NEIGHBORHOODS: string[] = [...new Set([
  ...SPACES.map((space) => space.neighborhood),
  "Aclimação", "Água Branca", "Alto da Lapa", "Barra Funda", "Bom Retiro", "Brooklin", "Brás",
  "Butantã", "Cambuci", "Campo Grande", "Campo Limpo", "Cangaíba", "Carrão", "Chácara Klabin",
  "Cidade Ademar", "Cidade Dutra", "Cidade Jardim", "Freguesia do Ó", "Grajaú", "Guaianases",
  "Interlagos", "Itaim Bibi", "Itaquera", "Jabaquara", "Jaguaré", "Jardim América", "Jardim Ângela",
  "Jardim Paulista", "Jardim São Luís", "Lapa", "Limão", "Morumbi", "Pacaembu", "Paraisópolis",
  "Parque do Carmo", "Pinheiros", "Pirituba", "Raposo Tavares", "Sacomã", "Santa Teresinha",
  "Santo Amaro", "São Miguel Paulista", "Sapopemba", "Socorro", "Sumaré", "Tremembé", "Tatuapé",
  "Vila Andrade", "Vila Leopoldina", "Vila Matilde", "Vila Olímpia", "Vila Prudente", "Vila Sônia",
])].sort((a, b) => a.localeCompare(b, "pt-BR"));

export function getSpaceBySlug(slug: string): Space | undefined {
  return SPACES.find((space) => space.slug === slug);
}

/** Atalhos da home: um espaço marcante por zona. */
export const FEATURED_SLUGS = [
  "campo-belo-aberto",
  "quintal-da-praca",
  "galpao-da-mooca",
  "arena-vila-guilherme",
  "terraco-bela-vista",
] as const;

export const FEATURED_SPACES: Space[] = FEATURED_SLUGS.map((slug) => {
  const space = getSpaceBySlug(slug);
  if (!space) throw new Error(`Espaço em destaque inexistente: ${slug}`);
  return space;
});
