export const ZONES = ["Centro", "Norte", "Sul", "Leste", "Oeste"] as const;
export const USE_TYPES = [
  "passeio",
  "brincadeira",
  "treino",
  "socializacao",
  "creche",
  "pernoite",
  "hospedagem",
] as const;
export const DOG_SIZES = ["pequeno", "medio", "grande"] as const;
export const AMENITIES = ["cercado", "gramado", "agua", "sombra", "agility"] as const;
export const TIME_SLOTS = ["manha", "tarde", "noite"] as const;
export const SPACE_TYPES = ["quintal", "campo", "salao", "agility", "piscina", "terraco"] as const;
/**
 * Sinais opcionais de acolhimento. Ficam fora de `AMENITIES` de propósito:
 * amenidade descreve o espaço, isto descreve como a casa recebe o cão. Nenhum
 * registro é obrigado a ter todos — o card usa só o que existe.
 */
export const STAY_FEATURES = [
  "ambiente-interno",
  "area-coberta",
  "jardim-cercado",
  "canto-de-descanso",
  "acompanhamento-noturno",
] as const;

export type Zone = (typeof ZONES)[number];
export type UseType = (typeof USE_TYPES)[number];
export type DogSize = (typeof DOG_SIZES)[number];
export type Amenity = (typeof AMENITIES)[number];
export type TimeSlot = (typeof TIME_SLOTS)[number];
export type SpaceType = (typeof SPACE_TYPES)[number];
export type StayFeature = (typeof STAY_FEATURES)[number];

export type Space = {
  slug: string;
  name: string;
  zone: Zone;
  neighborhoodLabel: string;
  /** Nome do bairro sem o prefixo, para busca e autocomplete. */
  neighborhood: string;
  approximateMapArea: string;
  spaceType: SpaceType;
  allowedUses: UseType[];
  dogSizes: DogSize[];
  maxDogs: number;
  availableSlots: TimeSlot[];
  amenities: Amenity[];
  imageUrl: string;
  imageAlt: string;
  description: string;
  /** Sinais de acolhimento, quando o espaço recebe para estadia. Opcional. */
  stayFeatures?: StayFeature[];
  /** Como é a rotina de acolhimento, em uma frase. Opcional. */
  stayNote?: string;
};

export const AMENITY_LABELS: Record<Amenity, string> = {
  cercado: "Área cercada",
  gramado: "Gramado",
  agua: "Água disponível",
  sombra: "Sombra",
  agility: "Itens de treino",
};

export const USE_TYPE_LABELS: Record<UseType, string> = {
  passeio: "Passeio tranquilo",
  brincadeira: "Brincadeira livre",
  treino: "Treino e adestramento",
  socializacao: "Socialização",
  creche: "Creche por um dia",
  pernoite: "Pernoite",
  hospedagem: "Hospedagem por vários dias",
};

/** Ocasiões em que o cão dorme fora: exigem espaço abrigado. */
export const OVERNIGHT_USES: UseType[] = ["pernoite", "hospedagem"];

export const DOG_SIZE_LABELS: Record<DogSize, string> = {
  pequeno: "Pequeno porte",
  medio: "Médio porte",
  grande: "Grande porte",
};

export const TIME_SLOT_LABELS: Record<TimeSlot, string> = {
  manha: "Manhã",
  tarde: "Tarde",
  noite: "Noite",
};

export const SPACE_TYPE_LABELS: Record<SpaceType, string> = {
  quintal: "Quintal",
  campo: "Campo aberto",
  salao: "Salão coberto",
  agility: "Circuito de treino",
  piscina: "Piscina para cães",
  terraco: "Terraço",
};

export const STAY_FEATURE_LABELS: Record<StayFeature, string> = {
  "ambiente-interno": "Ambiente interno",
  "area-coberta": "Área coberta",
  "jardim-cercado": "Jardim cercado",
  "canto-de-descanso": "Canto de descanso",
  "acompanhamento-noturno": "Acompanhamento à noite",
};

const photo = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=85`;

export const SPACES: Space[] = [
  // Centro
  {
    slug: "patio-santa-cecilia",
    name: "Pátio Santa Cecília",
    zone: "Centro",
    neighborhoodLabel: "Região de Santa Cecília",
    neighborhood: "Santa Cecília",
    approximateMapArea: "Centro, em um trecho residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "treino", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agility"],
    imageUrl: photo("1594498653385-d5172c532c00"),
    imageAlt: "Quintal gramado cercado por vegetação",
    description: "Quintal compacto para rotinas de treino e passeio no meio da cidade.",
    stayFeatures: ["canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Recebe até três cães por noite, cada um com o mesmo canto de descanso reservado.",
  },
  {
    slug: "terraco-bela-vista",
    name: "Terraço Bela Vista",
    zone: "Centro",
    neighborhoodLabel: "Região da Bela Vista",
    neighborhood: "Bela Vista",
    approximateMapArea: "Centro, em uma área de acesso fácil",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1624018171446-c4f0b942cf87"),
    imageAlt: "Terraço com jardim e canteiros floridos",
    description: "Terraço abrigado para encontros calmos com cães pequenos.",
    stayFeatures: ["area-coberta", "canto-de-descanso"],
    stayNote: "Terraço abrigado da chuva e do vento, com cama e água ao alcance durante a noite.",
  },
  {
    slug: "jardim-da-consolacao",
    name: "Jardim da Consolação",
    zone: "Centro",
    neighborhoodLabel: "Região da Consolação",
    neighborhood: "Consolação",
    approximateMapArea: "Centro, próximo a um corredor arborizado",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua"],
    imageUrl: photo("1778683326192-898fc982e6a6"),
    imageAlt: "Jardim cercado por muro de madeira",
    description: "Jardim reservado, bom para os primeiros encontros entre cães.",
    stayFeatures: ["jardim-cercado", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Jardim fechado para um grupo pequeno, com rotina calma de manhã e à noite.",
  },
  {
    slug: "salao-da-liberdade",
    name: "Salão da Liberdade",
    zone: "Centro",
    neighborhoodLabel: "Região da Liberdade",
    neighborhood: "Liberdade",
    approximateMapArea: "Centro, em uma quadra comercial",
    spaceType: "salao",
    allowedUses: ["treino", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "agility"],
    imageUrl: photo("1538307602205-80b5c2ff26ec"),
    imageAlt: "Área externa com mesas e piso coberto",
    description: "Salão coberto que resolve o dia de chuva sem cancelar o treino.",
    stayFeatures: ["ambiente-interno", "area-coberta", "canto-de-descanso"],
    stayNote: "Estadia toda em ambiente interno, com o mesmo lugar de descanso a cada noite.",
  },
  {
    slug: "quintal-higienopolis",
    name: "Quintal Higienópolis",
    zone: "Centro",
    neighborhoodLabel: "Região de Higienópolis",
    neighborhood: "Higienópolis",
    approximateMapArea: "Centro, em uma rua arborizada",
    spaceType: "quintal",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "sombra"],
    imageUrl: photo("1596481768453-8befafc2d7ae"),
    imageAlt: "Jardim de casa com caminho de pedras entre a vegetação",
    description: "Jardim de casa reservado, para um cão de cada vez e sem outros por perto.",
    stayFeatures: ["canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Recebe um cão de cada vez, sem outros por perto, do primeiro dia ao fim da estadia.",
  },
  {
    slug: "deck-da-republica",
    name: "Deck da República",
    zone: "Centro",
    neighborhoodLabel: "Região da República",
    neighborhood: "República",
    approximateMapArea: "Centro, perto de uma praça",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1561283890-5d858c23b2ea"),
    imageAlt: "Campo gramado aberto sob céu limpo",
    description: "Deck cercado para fim de tarde com outros tutores.",
  },

  {
    slug: "quintal-do-bom-retiro",
    name: "Quintal do Bom Retiro",
    zone: "Centro",
    neighborhoodLabel: "Região do Bom Retiro",
    neighborhood: "Bom Retiro",
    approximateMapArea: "Centro, entre a rua e o fundo de quadra",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "sombra", "agua"],
    imageUrl: photo("1681853108586-f29b4ef5c0fb"),
    imageAlt: "Quintal gramado cercado, com casas ao fundo",
    description: "Quintal fechado nos quatro lados, com grama baixa e portão único.",
    stayFeatures: ["jardim-cercado", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Quintal fechado nos quatro lados e com portão único: saída e volta sempre acompanhadas.",
  },
  {
    slug: "patio-do-cambuci",
    name: "Pátio do Cambuci",
    zone: "Centro",
    neighborhoodLabel: "Região do Cambuci",
    neighborhood: "Cambuci",
    approximateMapArea: "Centro, em rua sem saída",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1514373941175-0a141072bbc8"),
    imageAlt: "Campo gramado com banco e árvores",
    description: "Pátio calçado e cercado por muretas, bom para grupo pequeno.",
  },
  // Norte
  {
    slug: "campo-do-sol",
    name: "Campo do Sol",
    zone: "Norte",
    neighborhoodLabel: "Região de Santana",
    neighborhood: "Santana",
    approximateMapArea: "Norte, próximo a uma faixa de parques",
    spaceType: "campo",
    allowedUses: ["brincadeira", "passeio", "socializacao", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "sombra"],
    imageUrl: photo("1585107328143-be98f5f6119b"),
    imageAlt: "Campo aberto com grama alta e árvores",
    description: "Campo aberto para gastar energia com espaço de sobra.",
  },
  {
    slug: "patio-das-oliveiras",
    name: "Pátio das Oliveiras",
    zone: "Norte",
    neighborhoodLabel: "Região de Tucuruvi",
    neighborhood: "Tucuruvi",
    approximateMapArea: "Norte, próximo a áreas arborizadas",
    spaceType: "quintal",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1715934514075-06f0dbda1c09"),
    imageAlt: "Quintal cercado com grama e muro claro",
    description: "Pátio tranquilo para encontros e passeios sem pressa.",
    stayFeatures: ["canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Rotina sem pressa, com pátio à sombra de dia e canto reservado para dormir.",
  },
  {
    slug: "gramado-casa-verde",
    name: "Gramado Casa Verde",
    zone: "Norte",
    neighborhoodLabel: "Região da Casa Verde",
    neighborhood: "Casa Verde",
    approximateMapArea: "Norte, em uma área de casas",
    spaceType: "campo",
    allowedUses: ["brincadeira", "treino", "passeio", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "agility"],
    imageUrl: photo("1719324923613-ff0884b031ed"),
    imageAlt: "Gramado amplo ao lado de uma construção",
    description: "Gramado largo, pensado para cães que correm de verdade.",
  },
  {
    slug: "arena-vila-guilherme",
    name: "Arena Vila Guilherme",
    zone: "Norte",
    neighborhoodLabel: "Região de Vila Guilherme",
    neighborhood: "Vila Guilherme",
    approximateMapArea: "Norte, em uma zona mista",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira", "socializacao", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agility", "agua"],
    imageUrl: photo("1608200765700-ba7ff78b6dd0"),
    imageAlt: "Caminho de parque com cães ao fundo",
    description: "Circuito montado para treino de obstáculos, com foco em uma dupla por vez.",
  },
  {
    slug: "bosque-do-mandaqui",
    name: "Bosque do Mandaqui",
    zone: "Norte",
    neighborhoodLabel: "Região do Mandaqui",
    neighborhood: "Mandaqui",
    approximateMapArea: "Norte, em uma encosta arborizada",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "sombra", "agua"],
    imageUrl: photo("1695550056778-de79c8cd909e"),
    imageAlt: "Área de convívio ao ar livre com guarda-sol",
    description: "Bosque sombreado que aguenta grupos maiores sem ficar apertado.",
  },
  {
    slug: "quintal-do-jacana",
    name: "Quintal do Jaçanã",
    zone: "Norte",
    neighborhoodLabel: "Região do Jaçanã",
    neighborhood: "Jaçanã",
    approximateMapArea: "Norte, em um bairro residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "sombra"],
    imageUrl: photo("1719324924230-63781a3f18b9"),
    imageAlt: "Quintal com gramado e casa ao fundo",
    description: "Quintal cercado e reservado para cães pequenos.",
    stayFeatures: ["jardim-cercado", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Estadia pensada para cães pequenos, em quintal cercado e sem circulação de fora.",
  },

  {
    slug: "gramado-da-freguesia",
    name: "Gramado da Freguesia",
    zone: "Norte",
    neighborhoodLabel: "Região da Freguesia do Ó",
    neighborhood: "Freguesia do Ó",
    approximateMapArea: "Zona Norte, perto de uma área verde",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 8,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "sombra"],
    imageUrl: photo("1597022187576-c62f63e6c2a2"),
    imageAlt: "Campo gramado com cerca de madeira no fim da tarde",
    description: "Campo aberto e cercado, com espaço para turma inteira correr.",
  },
  {
    slug: "casa-do-tremembe",
    name: "Casa do Tremembé",
    zone: "Norte",
    neighborhoodLabel: "Região do Tremembé",
    neighborhood: "Tremembé",
    approximateMapArea: "Zona Norte, em rua residencial arborizada",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "sombra", "agua"],
    imageUrl: photo("1576897955702-24ad19680db3"),
    imageAlt: "Jardim com caminho de grama entre canteiros e uma casa",
    description: "Jardim de casa com caminho gramado, sombra e área coberta para dormir.",
    stayFeatures: ["jardim-cercado", "area-coberta", "ambiente-interno", "canto-de-descanso"],
    stayNote: "Jardim de casa durante o dia e área coberta para dormir, na mesma rotina todas as noites.",
  },
  // Sul
  {
    slug: "jardim-da-colina",
    name: "Jardim da Colina",
    zone: "Sul",
    neighborhoodLabel: "Região de Vila Mariana",
    neighborhood: "Vila Mariana",
    approximateMapArea: "Sul, em uma área residencial arborizada",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1602684379319-1de467ca74e5"),
    imageAlt: "Gramado cercado com árvores ao redor",
    description: "Jardim tranquilo para encontros em ritmo leve.",
    stayFeatures: ["canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Ritmo leve o dia inteiro, com sombra à tarde e um canto só para o descanso.",
  },
  {
    slug: "gramado-do-vale",
    name: "Gramado do Vale",
    zone: "Sul",
    neighborhoodLabel: "Região de Santo Amaro",
    neighborhood: "Santo Amaro",
    approximateMapArea: "Sul, em uma área de quintais amplos",
    spaceType: "campo",
    allowedUses: ["brincadeira", "treino", "socializacao", "passeio"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "agility"],
    imageUrl: photo("1612353413650-314b2f5146ed"),
    imageAlt: "Cães correndo em um campo gramado",
    description: "Gramado versátil, o mais flexível do catálogo para grupos.",
  },
  {
    slug: "recanto-do-ceu",
    name: "Recanto do Céu",
    zone: "Sul",
    neighborhoodLabel: "Região da Saúde",
    neighborhood: "Saúde",
    approximateMapArea: "Sul, perto de praças locais",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "sombra"],
    imageUrl: photo("1705980505348-222bc8724138"),
    imageAlt: "Área externa com piso e mobiliário de jardim",
    description: "Recanto arejado para a rotina de fim de tarde.",
  },
  {
    slug: "piscina-de-moema",
    name: "Piscina de Moema",
    zone: "Sul",
    neighborhoodLabel: "Região de Moema",
    neighborhood: "Moema",
    approximateMapArea: "Sul, em uma quadra residencial",
    spaceType: "piscina",
    allowedUses: ["brincadeira", "socializacao", "passeio", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1619333774340-3a878585c2e4"),
    imageAlt: "Área verde arborizada com sombra",
    description: "Piscina rasa para cães, com área de descanso na sombra.",
  },
  {
    slug: "campo-belo-aberto",
    name: "Campo Belo Aberto",
    zone: "Sul",
    neighborhoodLabel: "Região do Campo Belo",
    neighborhood: "Campo Belo",
    approximateMapArea: "Sul, em uma área plana",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "treino", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 8,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "sombra", "agility"],
    imageUrl: photo("1703733569670-f36996a8ca1d"),
    imageAlt: "Cães correndo juntos em gramado amplo",
    description: "O maior do catálogo: cabe grupo grande e aceita qualquer uso.",
  },
  {
    slug: "patio-do-ipiranga",
    name: "Pátio do Ipiranga",
    zone: "Sul",
    neighborhoodLabel: "Região do Ipiranga",
    neighborhood: "Ipiranga",
    approximateMapArea: "Sul, próximo a um parque histórico",
    spaceType: "quintal",
    allowedUses: ["passeio", "treino", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agility"],
    imageUrl: photo("1667230228326-c881966e2a29"),
    imageAlt: "Cães brincando em área cercada",
    description: "Pátio cercado para treino de cães maiores, sem plateia.",
    stayFeatures: ["jardim-cercado", "ambiente-interno", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Cães maiores ficam com espaço próprio, entre o pátio cercado e o ambiente interno.",
  },

  {
    slug: "quintal-do-jabaquara",
    name: "Quintal do Jabaquara",
    zone: "Sul",
    neighborhoodLabel: "Região do Jabaquara",
    neighborhood: "Jabaquara",
    approximateMapArea: "Zona Sul, em quadra residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "treino", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "sombra"],
    imageUrl: photo("1777115617638-5373f021de4f"),
    imageAlt: "Gramado amplo com árvore grande ao lado de casa de tijolos",
    description: "Terreno gramado grande ao lado da casa, com cerca em toda a volta.",
    stayFeatures: ["jardim-cercado", "ambiente-interno", "canto-de-descanso"],
    stayNote: "Terreno cercado ao lado da casa, com entrada para o ambiente interno quando o dia esquenta.",
  },
  {
    slug: "deck-do-brooklin",
    name: "Deck do Brooklin",
    zone: "Sul",
    neighborhoodLabel: "Região do Brooklin",
    neighborhood: "Brooklin",
    approximateMapArea: "Zona Sul, em condomínio baixo",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1766603636766-1f4662469448"),
    imageAlt: "Deck de madeira coberto, cercado de plantas",
    description: "Deck coberto e fechado, com sombra o dia inteiro e piso antiderrapante.",
    stayFeatures: ["area-coberta", "canto-de-descanso"],
    stayNote: "Deck coberto e fechado, com piso antiderrapante e lugar de descanso na sombra.",
  },
  {
    slug: "campo-de-interlagos",
    name: "Campo de Interlagos",
    zone: "Sul",
    neighborhoodLabel: "Região de Interlagos",
    neighborhood: "Interlagos",
    approximateMapArea: "Zona Sul, perto da represa",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "treino", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 8,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agua", "sombra", "agility"],
    imageUrl: photo("1558385952-504347abdceb"),
    imageAlt: "Pessoas e cães em gramado de parque",
    description: "Campo com árvores altas e cerca de madeira, bom para correr solto.",
  },
  // Leste
  {
    slug: "quintal-do-lago",
    name: "Quintal do Lago",
    zone: "Leste",
    neighborhoodLabel: "Região do Tatuapé",
    neighborhood: "Tatuapé",
    approximateMapArea: "Leste, em uma área de casas e praças",
    spaceType: "quintal",
    allowedUses: ["brincadeira", "socializacao", "passeio", "treino", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua"],
    imageUrl: photo("1592012428012-ba9d1cf9ad98"),
    imageAlt: "Gramado sob árvore grande, com cerca de madeira ao fundo",
    description: "Espaço aberto para cães que gostam de companhia.",
    stayFeatures: ["jardim-cercado", "ambiente-interno", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Boa estadia para cão que gosta de companhia: dia no gramado cercado, noite em lugar fixo.",
  },
  {
    slug: "jardim-do-arco",
    name: "Jardim do Arco",
    zone: "Leste",
    neighborhoodLabel: "Região de Anália Franco",
    neighborhood: "Anália Franco",
    approximateMapArea: "Leste, em uma área residencial",
    spaceType: "quintal",
    allowedUses: ["brincadeira", "treino", "passeio", "socializacao", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agility", "agua"],
    imageUrl: photo("1621851327323-bc467dd48d86"),
    imageAlt: "Cão correndo em gramado cercado",
    description: "Área aberta pensada para gastar energia com foco.",
  },
  {
    slug: "galpao-da-mooca",
    name: "Galpão da Mooca",
    zone: "Leste",
    neighborhoodLabel: "Região da Mooca",
    neighborhood: "Mooca",
    approximateMapArea: "Leste, em um trecho industrial revitalizado",
    spaceType: "salao",
    allowedUses: ["treino", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "agility"],
    imageUrl: photo("1780838446281-9394772d07a8"),
    imageAlt: "Pátio circular de pedra rodeado por vegetação",
    description: "Galpão coberto e cercado, útil quando o tempo fecha.",
    stayFeatures: ["ambiente-interno", "area-coberta", "canto-de-descanso"],
    stayNote: "Estadia coberta de ponta a ponta, sem depender do tempo lá fora.",
  },
  {
    slug: "campo-da-penha",
    name: "Campo da Penha",
    zone: "Leste",
    neighborhoodLabel: "Região da Penha",
    neighborhood: "Penha",
    approximateMapArea: "Leste, perto de uma área verde",
    spaceType: "campo",
    allowedUses: ["passeio", "brincadeira", "treino", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "sombra", "agua"],
    imageUrl: photo("1619316741699-b96740c17b63"),
    imageAlt: "Gramado extenso com árvores ao fundo",
    description: "Campo de manhã cedo, quando o movimento ainda é baixo.",
  },
  {
    slug: "circuito-vila-formosa",
    name: "Circuito Vila Formosa",
    zone: "Leste",
    neighborhoodLabel: "Região de Vila Formosa",
    neighborhood: "Vila Formosa",
    approximateMapArea: "Leste, em uma rua residencial",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira", "passeio", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agility"],
    imageUrl: photo("1703733574403-e2e42e3c5bda"),
    imageAlt: "Cães correndo em parque cercado",
    description: "Circuito de obstáculos dimensionado para cães menores.",
  },
  {
    slug: "terraco-do-belem",
    name: "Terraço do Belém",
    zone: "Leste",
    neighborhoodLabel: "Região do Belém",
    neighborhood: "Belém",
    approximateMapArea: "Leste, em uma quadra tranquila",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1512134687100-628ef82e6626"),
    imageAlt: "Gramado verde com árvores ao redor",
    description: "Terraço cercado, bom para cães pequenos e tímidos.",
    stayFeatures: ["area-coberta", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Terraço cercado e tranquilo, com rotina curta de saídas para cães mais tímidos.",
  },

  {
    slug: "quintal-de-itaquera",
    name: "Quintal de Itaquera",
    zone: "Leste",
    neighborhoodLabel: "Região de Itaquera",
    neighborhood: "Itaquera",
    approximateMapArea: "Zona Leste, em rua residencial",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "sombra"],
    imageUrl: photo("1621271654319-5e78a0f48756"),
    imageAlt: "Quintal gramado de casa com árvore e cerca alta no fim do dia",
    description: "Quintal gramado com cerca alta e um canto coberto para descanso.",
    stayFeatures: ["jardim-cercado", "area-coberta", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Quintal gramado de dia e canto coberto à noite, com cerca alta em toda a volta.",
  },
  {
    slug: "salao-vila-prudente",
    name: "Salão Vila Prudente",
    zone: "Leste",
    neighborhoodLabel: "Região da Vila Prudente",
    neighborhood: "Vila Prudente",
    approximateMapArea: "Zona Leste, em rua de galpões",
    spaceType: "salao",
    allowedUses: ["treino", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 8,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "agility"],
    imageUrl: photo("1771909719482-4f95e62f41a7"),
    imageAlt: "Salão coberto amplo com piso emborrachado",
    description: "Salão fechado e climatizado, aberto mesmo em dia de chuva.",
    stayFeatures: ["ambiente-interno", "area-coberta", "canto-de-descanso"],
    stayNote: "Salão fechado e climatizado, com espaço separado para o descanso de cada cão.",
  },
  // Oeste
  {
    slug: "quintal-da-praca",
    name: "Quintal da Praça",
    zone: "Oeste",
    neighborhoodLabel: "Região de Pinheiros",
    neighborhood: "Pinheiros",
    approximateMapArea: "Oeste, perto da área verde urbana",
    spaceType: "quintal",
    allowedUses: ["treino", "brincadeira", "passeio", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "sombra", "agility"],
    imageUrl: photo("1569203685368-118435c389dd"),
    imageAlt: "Cães correndo em gramado cercado",
    description: "Área ampla e cercada para treinar com espaço e foco.",
    stayFeatures: ["jardim-cercado", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Recebe poucos cães por vez, com área cercada de dia e lugar reservado para a noite.",
  },
  {
    slug: "bosque-claro",
    name: "Bosque Claro",
    zone: "Oeste",
    neighborhoodLabel: "Região do Butantã",
    neighborhood: "Butantã",
    approximateMapArea: "Oeste, em uma zona mais arborizada",
    spaceType: "campo",
    allowedUses: ["passeio", "treino", "brincadeira", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "sombra", "agility"],
    imageUrl: photo("1784593149239-7c0073ea5951"),
    imageAlt: "Quintal cercado por cerca de madeira",
    description: "Refúgio verde para uma rotina mais ativa.",
  },
  {
    slug: "casa-da-serra",
    name: "Casa da Serra",
    zone: "Oeste",
    neighborhoodLabel: "Região de Alto de Pinheiros",
    neighborhood: "Alto de Pinheiros",
    approximateMapArea: "Oeste, em área de casas",
    spaceType: "quintal",
    allowedUses: ["treino", "socializacao", "brincadeira", "passeio", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "agua", "agility"],
    imageUrl: photo("1758208137355-223fa672cbe2"),
    imageAlt: "Quintal de casa com gramado e cerca alta em toda a volta",
    description: "Quintal amplo de casa, fechado por cerca alta em toda a volta.",
    stayFeatures: ["jardim-cercado", "ambiente-interno", "canto-de-descanso"],
    stayNote: "Quintal amplo de casa, com acesso ao ambiente interno e cantos de descanso separados.",
  },
  {
    slug: "piscina-das-perdizes",
    name: "Piscina das Perdizes",
    zone: "Oeste",
    neighborhoodLabel: "Região de Perdizes",
    neighborhood: "Perdizes",
    approximateMapArea: "Oeste, em uma rua residencial",
    spaceType: "piscina",
    allowedUses: ["brincadeira", "socializacao", "passeio", "creche"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "agua", "sombra"],
    imageUrl: photo("1734079692147-c6fc9438a2d0"),
    imageAlt: "Jardim com deck de madeira e vegetação",
    description: "Piscina para cães com área seca ao lado para descanso.",
  },
  {
    slug: "patio-vila-madalena",
    name: "Pátio Vila Madalena",
    zone: "Oeste",
    neighborhoodLabel: "Região de Vila Madalena",
    neighborhood: "Vila Madalena",
    approximateMapArea: "Oeste, em uma ladeira tranquila",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 3,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra"],
    imageUrl: photo("1786654026603-54c654c05c18"),
    imageAlt: "Terraço com gramado e guarda-sol",
    description: "Pátio pequeno e reservado, no ritmo de quem quer sossego.",
    stayFeatures: ["area-coberta", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Pátio pequeno e reservado, no sossego de quem prefere pouco movimento.",
  },
  {
    slug: "arena-da-lapa",
    name: "Arena da Lapa",
    zone: "Oeste",
    neighborhoodLabel: "Região da Lapa",
    neighborhood: "Lapa",
    approximateMapArea: "Oeste, próximo a uma via movimentada",
    spaceType: "agility",
    allowedUses: ["treino", "brincadeira", "passeio", "socializacao"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 6,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["gramado", "agility", "agua"],
    imageUrl: photo("1684867430916-ede9dc95eca5"),
    imageAlt: "Terreno gramado delimitado por muro",
    description: "Arena de treino com espaço para turma inteira de adestramento.",
  },
  {
    slug: "jardim-de-vila-leopoldina",
    name: "Jardim da Vila Leopoldina",
    zone: "Oeste",
    neighborhoodLabel: "Região da Vila Leopoldina",
    neighborhood: "Vila Leopoldina",
    approximateMapArea: "Zona Oeste, em rua tranquila",
    spaceType: "quintal",
    allowedUses: ["passeio", "brincadeira", "socializacao", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "gramado", "sombra", "agua"],
    imageUrl: photo("1729058015948-592a8e4a1772"),
    imageAlt: "Grama alta iluminada pelo sol junto a uma cerca de madeira",
    description: "Gramado macio, cercado por tapume de madeira em toda a volta.",
    stayFeatures: ["jardim-cercado", "canto-de-descanso", "acompanhamento-noturno"],
    stayNote: "Gramado macio fechado por tapume em toda a volta, com rotina fixa de descanso.",
  },
  {
    slug: "terraco-do-sumare",
    name: "Terraço do Sumaré",
    zone: "Oeste",
    neighborhoodLabel: "Região do Sumaré",
    neighborhood: "Sumaré",
    approximateMapArea: "Zona Oeste, na cobertura de um prédio baixo",
    spaceType: "terraco",
    allowedUses: ["passeio", "socializacao", "brincadeira", "creche", "pernoite"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 4,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1762195804066-2fece9b24496"),
    imageAlt: "Terraço com bancos de madeira e vista da cidade",
    description: "Terraço fechado por grade alta, com sombra e vista aberta.",
  },
  {
    slug: "patio-do-morumbi",
    name: "Pátio do Morumbi",
    zone: "Oeste",
    neighborhoodLabel: "Região do Morumbi",
    neighborhood: "Morumbi",
    approximateMapArea: "Zona Oeste, no fundo de uma casa",
    spaceType: "quintal",
    allowedUses: ["passeio", "socializacao", "brincadeira", "treino", "creche", "pernoite", "hospedagem"],
    dogSizes: ["pequeno", "medio", "grande"],
    maxDogs: 5,
    availableSlots: ["manha", "tarde", "noite"],
    amenities: ["cercado", "sombra", "agua"],
    imageUrl: photo("1655109371498-30745747d279"),
    imageAlt: "Pátio calçado com casinha de madeira e canteiros",
    description: "Pátio de piso liso com casinha de madeira, fácil de limpar.",
    stayFeatures: ["area-coberta", "canto-de-descanso"],
    stayNote: "Casinha de madeira abrigada no pátio, de piso liso e fácil de manter limpo.",
  },
];

/** Bairros que hoje têm espaço no catálogo, para filtrar a busca. */
export const CATALOG_NEIGHBORHOODS: string[] = [...new Set(SPACES.map((space) => space.neighborhood))].sort((a, b) =>
  a.localeCompare(b, "pt-BR"),
);

/**
 * Bairros de São Paulo oferecidos no formulário de solicitação. Inclui os do
 * catálogo e outros bairros onde ainda não temos espaço, para que o tutor
 * consiga dizer onde precisa mesmo que a região ainda não esteja atendida.
 */
export const SP_NEIGHBORHOODS: string[] = [...new Set([
  ...SPACES.map((space) => space.neighborhood),
  "Aclimação", "Água Branca", "Alto da Lapa", "Barra Funda", "Bom Retiro", "Brooklin", "Brás",
  "Butantã", "Cambuci", "Campo Grande", "Campo Limpo", "Cangaíba", "Carrão", "Chácara Klabin",
  "Cidade Ademar", "Cidade Dutra", "Cidade Jardim", "Freguesia do Ó", "Grajaú", "Guaianases",
  "Interlagos", "Itaim Bibi", "Itaquera", "Jabaquara", "Jaguaré", "Jardim América", "Jardim Ângela",
  "Jardim Paulista", "Jardim São Luís", "Lapa", "Limão", "Morumbi", "Pacaembu", "Paraisópolis",
  "Parque do Carmo", "Pinheiros", "Pirituba", "Raposo Tavares", "Sacomã", "Santa Teresinha",
  "Santo Amaro", "São Miguel Paulista", "Sapopemba", "Socorro", "Sumaré", "Tremembé", "Tatuapé",
  "Vila Andrade", "Vila Leopoldina", "Vila Matilde", "Vila Olímpia", "Vila Prudente", "Vila Sônia",
])].sort((a, b) => a.localeCompare(b, "pt-BR"));

export function getSpaceBySlug(slug: string): Space | undefined {
  return SPACES.find((space) => space.slug === slug);
}

/** Atalhos da home: uma casa que recebe para estadia em cada zona. */
export const FEATURED_SLUGS = [
  "quintal-higienopolis",
  "casa-do-tremembe",
  "quintal-do-jabaquara",
  "quintal-de-itaquera",
  "casa-da-serra",
] as const;

export const FEATURED_SPACES: Space[] = FEATURED_SLUGS.map((slug) => {
  const space = getSpaceBySlug(slug);
  if (!space) throw new Error(`Espaço em destaque inexistente: ${slug}`);
  return space;
});
